### ISSUE TITLE
Submission TODO list

### ISSUE THREAD

**Issue by KamilSJaron** [KamilSJaron/genomic-features-of-asexual-animals#23]
**writing**

- [x] write a cover letter
- [x] update reference list for figure 1
- [x] adjust gene loss section accoring to the comments in the doc
- [x] correct the analysis or explain in the text
- [x] figure cryptobiosis in ref33 (fix p34, comment by reviewer # 4)
- [x] integrate reviwers comments to TEs section
- [x] update references (the reference placeholder is {cit} with a pointer in the comment)
- [x] regenerate **Supplementary figure 4** (TEs vs cellular mechanism) 
- [x] polish Heterozygosity Structure section
- [x] remove the Panadrolaimus strains
- [x] fix box 2 figure or text. (central / terminal fusion are messy and reverted terminal... it's not clear at all... We should focus on consequences of inheritance)
- [x] polish the first Result paragraph (explanation why we have this strange hybrid between a review and research paper)
- [x] integrate reviwers comments to Palindrome section
- [x] S4 text - bdelloid rotifer genomics
- [x] update numbering for supplementary figures (they all shift by one; the main text needs to be adjusted appropriately)

**computing**

- [ ] linked HGT with SwissProt database
- [x] update all supplementary tables
- [x] figure out what is going to with _A. ricciae_ dnaPipeTE analysis (#22 )
- [x] get dnaPipeTE of _P. fallax_ (running)
- [x] regenerate Figure 4: TEs
- [x] redo dnaPipeTE of Mbel1 (#18)
- [x] get dnaPipeTE estimates of three honeybee genomes (#19 running)
- [x] tardigrade GenomeScope on filtered reads
- [x] est. number of palindromes in Mbel1 (me) (#18)

**Comment by KamilSJaron** [comment]
- [ ] linked HGT with SwissProt database ???

**Comment by KamilSJaron** [comment]
I just reordered the supplementary sections by the appearance in the text! I triple check every reference, but if you would spot something odd, don't hesitate to report it.
